### PR TITLE
[ADD] outplacement_final_report: AFC-2407 Added PDF report to print F…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…inal report and Added button to send final report via email.

### CODE REVIEW

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 could you please add usergrup "technical settings" to the "Final Report"?
Both for the new "Send by email"-button Action->"Print" and the "Chatter"-log-records.
The reason is that I would like to test the code on the test-servers, but I do not want to to show for everybody yet.

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel I've pushed one more commit here to Hide Report and button. Added Technical Feature group on both.
But I didn't found a way to add user-group on particular log message.

**Comment by fredrikarvas-vertel** [comment]
Thanks!

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145  We keep this branch open for some time, since it will need some modifications

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Pull request merged**
